import type { Metadata } from "next";

import { Noto_Sans_KR, Nanum_Gothic_Coding } from "next/font/google";
import "./globals.css";

const notoSansKR = Noto_Sans_KR({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

const nanumGothicCoding = Nanum_Gothic_Coding({
  variable: "--font-nanum-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${notoSansKR.variable} ${nanumGothicCoding.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
